accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('join/', views.join, name='join'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('settings/', views.settings, name='settings'),
    path('password/', views.change_password, name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('search/', views.search, name='search'),
    path('<int:article_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/child_comment_create/<int:comment_pk>/', views.child_comment_create, name='child_comment_create'),
    path('<int:article_pk>/child_comment_delete/<int:child_comment_pk>/', views.child_comment_delete, name='child_comment_delete'),
]

django_pjt_hashtag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from community import views

urlpatterns = [
    path('', views.index),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

community/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='articles')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)

    def __str__(self):
        return f'{self.title}'

class Comment(models.Model):
    content = models.CharField(max_length=100)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,null=True, related_name='comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    parent_comment = models.ForeignKey("self", on_delete=models.PROTECT, related_name='child_comments', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.content}'

class Hashtag(models.Model):
    tag = models.CharField(max_length=15)
    has_articles = models.ManyToManyField(Article, related_name='has_hashtags', blank=True)

    def __str__(self):
        return f'{self.tag}'

community/forms.py
from django import forms
from .models import Article, Comment, Hashtag

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        max_length=100,
        label='',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Minigram은 건전한 댓글 문화를 지향합니다.'
            })
    )

    class Meta:
        model = Comment
        fields = ['content']

community/views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.db.models import Count, Prefetch
from django.contrib.auth import get_user_model
from django.http import HttpResponse, JsonResponse
import json

# Create your views here.


def index(request):
    articles = Article.objects.select_related('creator').prefetch_related(
        'like_users').annotate(like_users_count=Count('like_users')).order_by('-pk')
    term = None
    context = {
        'articles': articles,
        'term': term
    }
    return render(request, 'community/index.html', context)


@require_POST
@login_required
def post(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.creator = request.user
            article.save()

            hashtags = request.POST['hashtags'].split('#')[1:]
            for hashtag in hashtags:
                if not Hashtag.objects.filter(tag=hashtag).exists():
                    h = Hashtag()
                    h.tag = hashtag.strip()
                    h.save()
                else:
                    h = Hashtag.objects.get(tag=hashtag)

                h.has_articles.add(article)
            messages.success(request, '글을 성공적으로 게시하였습니다.')
            return redirect('community:index')
        else:
            messages.error(request, '글 작성에 실패하였습니다.')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'community/form.html', context)


@require_POST
@login_required
def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)

    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
        liked = False
    else:
        article.like_users.add(request.user)
        liked = True

    context = {
        'liked': liked,
        'count': article.like_users.count()
    }
    return JsonResponse(context)


@login_required
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    child_comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form,
        'child_comment_form': child_comment_form,
    }
    return render(request, 'community/detail.html', context)


@login_required
def edit(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.creator:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                for hashtag in article.has_hashtags.all():
                    hashtag.delete()

                article = form.save(commit=False)
                article.creator = request.user
                article.save()

                hashtags = request.POST['hashtags'].split('#')[1:]
                for hashtag in hashtags:
                    if not Hashtag.objects.filter(tag=hashtag).exists():
                        h = Hashtag()
                        h.tag = hashtag.strip()
                        h.save()
                    else:
                        h = Hashtag.objects.get(tag=hashtag)

                    h.has_articles.add(article)
                messages.success(request, '글을 성공적으로 수정하였습니다.')
                return redirect('community:detail', article_pk)
            else:
                messages.error(request, '글 수정에 실패하였습니다.')
        else:
            form = ArticleForm(instance=article)
            hashtags = ''
            for hashtag in article.has_hashtags.all():
                hashtags += f'#{hashtag.tag}'
        context = {
            'form': form,
            'hashtags': hashtags
        }
        return render(request, 'community/form.html', context)
    else:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('community:detail', article_pk)


def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST' and request.user.is_authenticated and request.user == article.creator:
        article.delete()
    return redirect('community:index')


def search(request):
    term = request.GET.get('term')
    is_exist = Hashtag.objects.filter(tag=term).exists()
    if is_exist:
        hashtag = Hashtag.objects.get(tag=term)
        articles = Article.objects.filter(has_hashtags=hashtag)
    else:
        articles = []
    context = {
        'articles': articles,
        'term': term,
    }
    return render(request, 'community/index.html', context)


@login_required
@require_POST
def comment_create(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.creator = request.user
        comment.article = article
        comment.save()
        messages.success(request, '댓글을 성공적으로 작성하였습니다.')
    else:
        messages.error(request, '댓글 작성에 실패하였습니다.')
    return redirect('community:detail', article_pk)


@login_required
@require_POST
def child_comment_create(request, article_pk, comment_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        child_comment = form.save(commit=False)
        child_comment.creator = request.user
        child_comment.article = article
        child_comment.parent_comment = comment
        child_comment.save()
        messages.success(request, '대댓글을 성공적으로 작성하였습니다.')
    else:
        messages.error(request, '댓글 작성에 실패하였습니다.')
    return redirect('community:detail', article_pk)


@login_required
def comment_delete(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.creator:
        if not comment.child_comments.all():
            comment.delete()
            messages.success(request, '댓글을 삭제하였습니다.')
        else:
            messages.warning(request, '대댓글이 있는 댓글은 삭제할 수 없습니다.')
    else:
        messages.error(request, '댓글 삭제 권한이 없습니다.')
    return redirect('community:detail', article_pk)


@login_required
def child_comment_delete(request, article_pk, child_comment_pk):
    child_comment = get_object_or_404(Comment, pk=child_comment_pk)
    if request.user == child_comment.creator:
        child_comment.delete()
        messages.success(request, '댓글을 삭제하였습니다.')
    else:
        messages.error(request, '댓글 삭제 권한이 없습니다.')
    return redirect('community:detail', article_pk)

community/templates/community/__child_comment.html
{% load bootstrap4 %}

<ul class="comments-list child-comments-list mt-2">
    {% for child_comment in comment.child_comments.all %}
    <li class="comment mb-1">
    <div class="d-flex justify-content-between">
        <div>
        ⎿
        <a href="{% url 'accounts:profile' child_comment.creator.username %}"><small class="comment__creator ml-2">{{ child_comment.creator.username }}</small></a>
        <span class="comment__content">{{ child_comment.content }}</span>
        <span class="js-add-child-comment text-secondary">답글달기</span>
        {% if request.user == child_comment.creator %}
        <a href="{% url 'community:child_comment_delete' article.pk child_comment.pk %}" class="text-secondary">삭제하기</a>
        {% endif %}
        </div>
        <div>
            <small class="text-right text-secondary text-right">{{ child_comment.created_at }}</small>
        </div>
    </div>

    <form class="js-child-comment-form child-comment-form my-2" method="POST" action="{% url 'community:child_comment_create' article.pk child_comment.pk %}">
      {% csrf_token %}
      {% bootstrap_form child_comment_form %}
      <button class="btn btn-sm btn-secondary">
          댓글 작성
      </button>
    </form>

    {% with child_comment as comment %}
        {% if comment.child_comments.all %}
          {% include 'community/__child_comment.html'%}
        {% endif %}
    {% endwith %}

    </li>
    {% endfor %}
</ul>

community/templates/community/_card.html
{% load humanize %}

<div class="col col-md-6 col-lg-4 mb-4">
  <div class="card" style="width: 18rem;">
    <a href="{% url 'community:detail' article.pk %}">
      <div class="card-body">
        <h5 class="card-title">
          {{ article.title|slice:":23" }}...
        </h5>
        <hr />
        <h6 class="card-subtitle mb-2 text-muted updated">
          {{ article.updated_at|naturaltime }} 수정됨
        </h6>
        <p class="card-text">
          {{ article.content|slice:":100" }}...
        </p>
      </div>
    </a>
    <div class="card-footer">
      <a
        href="{% url 'accounts:profile' article.creator.username %}"
        class="card-link"
        >{{ article.creator.username }}</a
      >
      <div>
        <button type="button" class="btn btn-sm btn-light border border-danger" data-toggle="modal" data-target="#likeModal_{{ article.pk }}">
          <i class="fas fa-heart"></i><span id="like-count-{{ article.pk }}"class="badge badge-light">{{ article.like_users_count }}</span>
        </button>
        {% if request.user.is_authenticated %}
          {% if request.user in article.like_users.all %}
            <div class="btn btn-sm btn-secondary like-btn js-like" data-id="{{ article.pk }}">좋아요 취소</div>
          {% else %}
            <div class="btn btn-sm btn-secondary like-bt js-like" data-id="{{ article.pk }}">좋아요</div>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</div>

<!-- LikeModal -->
<div class="modal fade" id="likeModal_{{ article.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">이 글을 좋아하는 사람</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul>
          {% for liker in article.like_users.all %}
          <li class="liker badge badge-pill badge-info ">{{ liker.username }}</li>
          {% empty %}
          아직 이 글을 좋아하는 사람이 없습니다.
          {% endfor %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

community/templates/community/_comment.html
{% load bootstrap4 %}

<ul class="comments-list mt-4">
{% for comment in article.comments.all %}
  {% if not comment.parent_comment %}
  <li class="comment mb-3">
    <div class="d-flex justify-content-between">
      <div>
        <a href="{% url 'accounts:profile' comment.creator.username %}"><small class="comment__creator ml-2">{{ comment.creator.username }}</small></a>
        <span class="comment__content">{{ comment.content }}</span>
        <span class="js-add-child-comment text-secondary">답글달기</span>
        {% if request.user == comment.creator %}
        <a href="{% url 'community:comment_delete' article.pk comment.pk %}" class="text-secondary">삭제하기</a>
        {% endif %}
      </div>
      <div>
          <small class="text-right text-secondary text-right">{{ comment.created_at }}</small>
      </div>
    </div>

    <form class="js-child-comment-form child-comment-form my-2" method="POST" action="{% url 'community:child_comment_create' article.pk comment.pk %}">
      {% csrf_token %}
      {% bootstrap_form child_comment_form %}
      <button class="btn btn-sm btn-secondary">
          댓글 작성
      </button>
    </form>

    {% if comment.child_comments.all %}
      {% include 'community/__child_comment.html'%}
    {% endif %}

  </li>
  {% endif %}
{% empty %}
  <li>아직 댓글이 없습니다.</li>
{% endfor %}
</ul>

community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap4 static %}

{% block title %}
detail    
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'community/stylesheets/detail.css' %}"/>
    <link rel="stylesheet" href="{% static 'stylesheets/modal.css' %}"/>
{% endblock %}

{% block js %}
  <script src="{% static 'community/js/child_comment.js' %}"></script>
  <script src="{% static 'community/js/like_detail.js' %}"></script>
{% endblock %}

{% block body %}
<article class="mb-4">
  <div class="d-flex justify-content-between mb-3 header">
    <h3>{{ article.title }} <small>| <a class="badge badge-pill badge-primary" href="{% url 'accounts:profile' article.creator.username %}">{{ article.creator.username }}</a></small></h3>
    <div class="like-wrapper">
      <button type="button" class="btn btn-sm btn-light border border-danger" data-toggle="modal" data-target="#likeModal">
        <i class="fas fa-heart"></i><span class="badge badge-light">{{ article.like_users.count }}</span>
      </button>
      {% if request.user in article.like_users.all %}
        <div class="card-link btn btn-sm btn-secondary like-btn js-like">좋아요 취소</div>
      {% else %}
        <div class="card-link btn btn-sm btn-danger like-btn js-like">좋아요</div>
      {% endif %}
    </div>
  </div>
  <hr>

  <p class="mb-5">{{ article.content }}</p>

  <ul class="tag-list">
    {% for hashtag in article.has_hashtags.all %}
    <li class="tag badge badge-pill badge-info"><a class="text-white" href={{ "/community/search?term="|add:hashtag.tag }} >{{ hashtag.tag }}</a></li>
    {% endfor %}
  </ul>

  <p class="small my-0 text-right text-secondary">{{ article.updated_at }} (updated)</p>
  <p class="small my-0 text-right text-secondary">{{ article.created_at }} (created)</p>
  <div class="w-100 d-flex justify-content-between mt-3">
    <a class="btn btn-secondary w-25" href="{% url 'community:index' %}">Back</a>
    {% if request.user == article.creator %}
    <a class="btn btn-primary w-25" href="{% url 'community:edit' article.pk %}">Edit</a>
    <button type="button" class="btn btn-danger w-25" data-toggle="modal" data-target="#staticBackdrop">Delete</button>
    {% endif %}
  </div>
</article>

<section>
  <form class="js-comment-form" method="POST" action="{% url 'community:comment_create' article.pk %}">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button class="btn btn-sm btn-primary">
        댓글 작성
    </button>
  </form>

  {% if article.comments.all %}
    {% include 'community/_comment.html' %}
  {% endif %}
</section>


<!-- LikeModal -->
<div class="modal fade" id="likeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">이 글을 좋아하는 사람</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul>
          {% for liker in article.like_users.all %}
          <li class="liker badge badge-pill badge-info ">{{ liker.username }}</li>
          {% empty %}
          아직 이 글을 좋아하는 사람이 없습니다.
          {% endfor %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

  <!-- DeleteModal -->
  <div class="modal fade" id="staticBackdrop" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">경고</h5>
        </div>
        <div class="modal-body">
          삭제하시겠습니까?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary py-1" data-dismiss="modal">Cancel</button>
          <form action="{% url 'community:delete' article.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger py-1">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

community/templates/community/form.html
{% extends 'base.html' %}
{% load bootstrap4 static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'community/stylesheets/form.css' %}"/>
{% endblock %}

{% block title %}
    {% if request.resolver_match.url_name == 'post' %}
        Post
    {% elif request.resolver_match.url_name == 'edit' %}
        edit
    {% endif %}
{% endblock %}

{% block body %}
<h3>
    {% if request.resolver_match.url_name == 'post' %}
        Post
    {% elif request.resolver_match.url_name == 'edit' %}
        edit
    {% endif %}
</h3>
<hr>

<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input placeholder="#으로 시작하는 태그를 달아주세요" type="text" name="hashtags" value="{{ hashtags }}" />
    <div class="buttons">
        <a href="/" class="btn btn-secondary text-white">Back</a>
        <button class="btn btn-primary">
            Submit
        </button>
    <div>
</form>
{% endblock %}

community/templates/community/index.html
{% extends 'base.html' %}
{% load bootstrap4 static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'community/stylesheets/card.css' %}"/>
    <link rel="stylesheet" href="{% static 'stylesheets/modal.css' %}"/>
{% endblock %}

{% block js %}
  <script src="{% static 'community/js/like_index.js' %}"></script>
{% endblock %}

{% block title %}
    Home
{% endblock %}

{% block body %}

{% if request.resolver_match.url_name == 'search' %}
<h3>
    '{{ term }}' 검색 결과:
</h3>
{% endif %}
<hr>

<div class="row row-cols-1 row-cols-md-3">
  {% for article in articles %}
    {% include 'community/_card.html' %}
  {% empty %}
  <div>글이 없습니다.</div>
  {% endfor %}
</div>

{% endblock %}