accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('join/', views.join, name='join'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('settings/', views.settings, name='settings'),
    path('password/', views.change_password, name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

django_pjt_hashtag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from community import views

urlpatterns = [
    path('', views.index),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='follows', blank=True)

    def __str__(self):
        return f'{self.username}'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ['username']

class CustomPasswordChangeForm(PasswordChangeForm):
    model = get_user_model()

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login as user_login, logout as user_logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm
from django.contrib.auth.decorators import login_required

def join(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                messages.success(request, '회원님, 환영합니다.')
                new_user = form.save()
                user_login(request, new_user)
                return redirect('community:index')
            else:
                messages.error(request, '회원가입에 실패하였습니다.')
        else:
            form = CustomUserCreationForm()
        context = {
            'form': form
        }
    else:
        messages.error(request, '이미 로그인되어 있습니다.')
        return redirect('community:index')
    return render(request, 'accounts/form.html', context)

def login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                messages.success(request, '회원님, 반갑습니다.')
                user_login(request, form.get_user())
                return redirect('community:index')
            else:
                messages.error(request, '로그인에 실패하였습니다.')
        else:
           form = AuthenticationForm()
        context = {
            'form': form
        }
    else:
        messages.error(request, '이미 로그인되어 있습니다.')
        return redirect('community:index')
    return render(request, 'accounts/form.html', context)


def logout(request):
    if request.user.is_authenticated:
        user_logout(request)
    return redirect('community:index')

@login_required
def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    context = {
        'person': person
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def settings(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, '회원정보가 성공적으로 변경되었습니다.')
            return redirect('accounts:profile', request.user.username)
        else:
            messages.error(request, '회원정보 변경에 실패하였습니다.')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, '비밀번호가 성공적으로 변경되었습니다.')
        else:
            messages.error(request, '비밀번호 변경에 실패하였습니다.')
    else:
        form = CustomPasswordChangeForm(user=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

@login_required
def delete(request):
    request.user.delete()
    messages.error(request, '계정이 삭제되었습니다.')
    return redirect('community:index')

@login_required
def follow(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    if request.user in person.followers.all():
        person.followers.remove(request.user)    
    else:
        person.followers.add(request.user)    

    return redirect('accounts:profile', username)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    {% if request.resolver_match.url_name == 'join' %}
    Join
    {% elif request.resolver_match.url_name == 'login' %}
    Login
    {% elif request.resolver_match.url_name == 'settings' %}
    Settings
    {% elif request.resolver_match.url_name == 'change_password' %}
    Change Password
    {% endif %}
{% endblock %}

{% block body %}
<h3>
    {% if request.resolver_match.url_name == 'join' %}
    Join
    {% elif request.resolver_match.url_name == 'login' %}
    Login
    {% elif request.resolver_match.url_name == 'settings' %}
    Settings
    {% elif request.resolver_match.url_name == 'change_password' %}
    Change Password
    {% endif %}
</h3>
<hr>

<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <a href="/" class="btn btn-secondary text-white">Back</a>
    <button class="btn btn-primary">
        {% if request.resolver_match.url_name == 'join' %}
        Join
        {% elif request.resolver_match.url_name == 'login' %}
        Login
        {% elif request.resolver_match.url_name == 'settings' %}
        Confirm
        {% elif request.resolver_match.url_name == 'change_password' %}
        Change Password
        {% endif %}
    </button>
    {% if request.resolver_match.url_name == 'settings' %}
    <a href="{% url 'accounts:delete' %}" class="btn btn-danger text-white">Remove Account</a>
    {% endif %}
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 static humanize %}

{% block title %}
    {{ person.username }}
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'community/stylesheets/card.css' %}"/>
  <link rel="stylesheet" href="{% static 'stylesheets/profile.css' %}"/>
  <link rel="stylesheet" href="{% static 'stylesheets/modal.css' %}"/>
{% endblock %}


{% block body %}
<div class="header">
    {% if request.user == person %}
    <h3> 나의 프로필</h3>
    {% else %}
    <h3>{{ person.username }}님의 프로필</h3>
    {% endif %}
    {% if request.user != person %}
        {% if request.user in person.followers.all %}
            <a href="{% url 'accounts:follow' person.username %}"><button class="btn btn-secondary">팔로우 취소</button></a>
        {% else %}
            <a href="{% url 'accounts:follow' person.username %}"><button class="btn btn-primary">팔로우</button></a>
        {% endif %}
    {% endif %}
  </div>
<hr>

<div class="follow-info">
  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#followersModal">
  팔로워 <span class="badge badge-light">{{ person.followers.count }}</span>
  </button>
  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#followsModal">
  팔로우 <span class="badge badge-light">{{ person.follows.count }}</span>
  </button>
</div>
<hr>

<div class="user-create">
    {% if request.user == person %}
    <h4>내가 작성한 글 | {{ person.articles.count }} 개</h4>
    {% else %}
    <h4>{{ person.username }}님이 작성한 글 <small>({{ person.articles.count }} 개)</small></h4>
    {% endif %}

    <div class="row row-cols-1 row-cols-md-3">
        {% for article in person.articles.all %}
          {% include 'community/_card.html' %}
        {% empty %}
        <div class="col"> 아직 작성한 글이 없습니다. </div>
        {% endfor %}
    </div>
</div>
<hr>

<div class="user-like">
    {% if request.user == person %}
    <h4>내가 좋아요한 글 | {{ person.like_articles.count }} 개</h4>
    {% else %}
    <h4>{{ person.username }}님이 좋아요한 글 | {{ person.like_articles.count }} 개</h4>
    {% endif %}

    <div class="row row-cols-1 row-cols-md-3">
        {% for article in person.like_articles.all %}
          {% include 'community/_card.html' %}
        {% empty %}
        <div class="col"> 아직 좋아요한 글이 없습니다. </div>
        {% endfor %}
    </div>
</div>

<!-- followersModal -->
<div class="modal fade" id="followersModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ person.username }}님을 팔로잉하는 사람</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul>
          {% for follower in person.followers.all %}
          <li class="follower badge badge-pill badge-info ">{{ follower.username }}</li>
          {% empty %}
          아직 팔로워가 없습니다.
          {% endfor %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- followsModal -->
<div class="modal fade" id="followsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ person.username }}님이 팔로우하는 사람</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul>
          {% for follow in person.follows.all %}
          <li class="follow badge badge-pill badge-info ">{{ follow.username }}</li>
          {% empty %}
          아직 팔로우하는 사람이 없습니다.
          {% endfor %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}