accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('join/', views.join, name='join'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('settings/', views.settings, name='settings'),
    path('password/', views.change_password, name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('search/', views.search, name='search'),
    path('<int:article_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/child_comment_create/<int:comment_pk>/', views.child_comment_create, name='child_comment_create'),
    path('<int:article_pk>/child_comment_delete/<int:child_comment_pk>/', views.child_comment_delete, name='child_comment_delete'),
]

django_pjt_hashtag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from community import views

urlpatterns = [
    path('', views.index),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/_nav.html
{% load bootstrap4 %}

<div class="bg-dark px-5 navbar-wrapper">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark container justify-content-between">
    <a class="navbar-brand text-warning" href="{% url 'community:index' %}">Minigram</a>

    <form class="form-inline my-2 my-lg-0" action="{% url 'community:search' %}">
      <input class="form-control mr-sm-2" name="term" type="search" placeholder="Search by hashtag" aria-label="Search">
    </form>

    <div>
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
          <li class="nav-item mr-2">
            <a class="nav-link btn btn-sm btn-secondary text-white" href="{% url 'community:post' %}">Post</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle btn btn-sm btn-secondary text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'accounts:profile' request.user.username %}">Profile</a>
              {% comment %} <a class="dropdown-item" href="#">Favorites</a> {% endcomment %}
              <a class="dropdown-item" href="{% url 'accounts:settings' %}">Settings</a>
              <a class="dropdown-item" href="{% url 'accounts:logout'%}">Sign Out</a>
            </div>
          </li>
        {% else %}
          <li class="nav-item mr-2">
            <a href="{% url 'accounts:join' %}"><button class="btn btn-info">
              Join Now
            </button></a>
          </li>
          <li class="nav-item mr-2">
            <a class="nav-link text-white" href="{% url 'accounts:login' %}">Sign In</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title>{% block title %}{% endblock %} | Minigram</title>
    {% bootstrap_css %}
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" />
    <link rel="stylesheet" href="{% static 'stylesheets/global.css' %}"/>
    {% block css %}{% endblock %}
  </head>
  <body>
    {% include '_nav.html' %}

    {% if messages %}
      {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}

    <main class='container mt-5'>
    {% block body %}
    {% endblock %}
    </main>
    
    {% bootstrap_javascript jquery='full' %}
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    {% block js %}{% endblock %}
  </body>
</html>